name: classification

data:
  data_root: data/cifar10
  dataset: cifar10
  batch_size: 4096
  num_workers: 8

# model for data
model:
  _target_: models.ConvNet3
  num_classes: 10

# optimizer for training task model
optimizer:
  _target_: torch.optim.SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

# lr scheduler for training task optimizer
lr_scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones: [30, 60, 90, 100]
  gamma: 0.2

all_epoch: 250
random_seed_num: 200
start_save_epoch: 150
# train_layer: ['layer4.1.bn1.weight', 'layer4.1.bn1.bias', 'layer4.1.bn2.bias', 'layer4.1.bn2.weight'] # resnet18
# train_layer: ['conv1.weight','conv1.bias','conv2.weight','conv2.bias','conv3.weight','conv3.bias','fc.weight','fc.bias']  # convnet3
train_layer:  'all'

# parameter data root
param:
  data_root: param_data/cifar100_resnet18_k200/data.pt
  k: 200
  num_workers: 4

cond1:
  data_root: param_data/cifar100_resnet18_k200/data.pt
  k: 200
  num_workers: 4

cond2:
  data_root: param_data/cifar100_resnet18_k200/data.pt
  k: 200
  num_workers: 4
